### ISSUE TITLE
Is it possible to have impala ? 

### ISSUE THREAD

**Issue by ahoy-jon** [jetoile/hadoop-unit#88]
I don't know if it is a large request, knowing Impala is in C++. @jetoile If you have some time, we can chat about it.

**Comment by jetoile** [comment]
Hi @ahoy-jon 
Hum... I think supporting Impala will be quite a pain... since no binaries are available and building it is quite complicated...
With Hadoop Unit version 3.x, it will be possible to create your own plugin. 
I think that if your plugin use TestContainer, it should be possible to do something :P

**Comment by ahoy-jon** [comment]
Thanks for the informations.
I tried to build the thing on docker, it is not stable, I will try it again on day ! :)
